name: ACEMAGIC S1 Status
version: "1.0.2"
slug: acemagic_s1_status
description: Affiche Home Assistant OK avec CPU et RAM sur l'ecran LCD ACEMAGIC S1
url: https://github.com/Yeoh37/ha-acemagic-s1-display
arch:
  - amd64
startup: services
boot: auto
init: false
udev: true
privileged:
  - SYS_RAWIO
devices:
  - /dev/hidraw0
  - /dev/hidraw1
options:
  refresh_seconds: 10
  hidraw_device: auto
  orientation: landscape
schema:
  refresh_seconds: int
  hidraw_device: str
  orientation: list(auto|landscape|portrait)
